apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrations
  labels:
    app: drf  
spec:
  template:
    metadata:
      name: django-migrations
    spec:
      containers:
        - name: migrations
          image: tanvibhaktasb/django-drf:latest    
          command: ['python', 'manage.py', 'migrate']
          envFrom:
          - configMapRef:
              name: mysql-job-config
          volumeMounts:
            - name: mysql-job-config
              mountPath: /etc/config
      volumes:
      - name: mysql-job-config
        configMap:
          name: mysql-job-config 
      restartPolicy: Never
  backoffLimit: 2
