apiVersion: v1
kind: Service
metadata:
  labels:
    app: drf
  name: drf-lb
  namespace: default
  resourceVersion: "1520806"
spec:
  clusterIP: 10.11.248.110
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32258
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: drf  
  sessionAffinity: None
  type: LoadBalancer
