apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  labels: 
    app: mysql
data:
  MYSQL_DATABASE: "snippets"
  MYSQL_USER: "sb"
  MYSQL_HOST: "127.0.0.1"
  MYSQL_PASSWORD: "isthisapassword"
